=== anhtuan161295/com.my.express.news/src/main/vfs/system/modules/com.my.express.news/schemas/article.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xsd:include schemaLocation="opencms://opencms-xmlcontent.xsd"/>
	<xsd:include schemaLocation="opencms://system/modules/com.my.express.news/schemas/nested/article-list.xsd"/>

	<xsd:element name="ExpressNewsArticles" type="OpenCmsExpressNewsArticles"/>

	<xsd:complexType name="OpenCmsExpressNewsArticles">
		<xsd:sequence>
			<xsd:element name="ExpressNewsArticle" type="OpenCmsExpressNewsArticle" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="OpenCmsExpressNewsArticle">
		<xsd:sequence>
			<xsd:element name="Title" type="OpenCmsString" />
			<xsd:element name="ShortDescription" type="OpenCmsString" />
			<xsd:element name="Thumbnail" type="OpenCmsVfsFile" />
			<xsd:element name="VideoLink" type="OpenCmsVarLink" />
			<xsd:element name="Content" type="OpenCmsString" />
			<xsd:element name="Categories" type="OpenCmsVarLink" minOccurs="0" maxOccurs="unbounded" />
			<!--<xsd:element name="RelatedArticles" type="OpenCmsArticleList" />-->
			<xsd:element name="Date" type="OpenCmsString" />
			<xsd:element name="Comment" type="OpenCmsString"/>
			<xsd:element name="View" type="OpenCmsString"/>
			<xsd:element name="Like" type="OpenCmsString"/>
		</xsd:sequence>
		<xsd:attribute name="language" type="OpenCmsLocale" use="optional"/>
	</xsd:complexType>

	<xsd:annotation>
		<xsd:appinfo>
			<mappings>
				<mapping element="Title" mapto="property:Title" />
				<mapping element="Title" mapto="urlName" />
			</mappings>
			<defaults>
				<default element="Title" value="Add a new title here" />
			</defaults>
			<layouts>
				<layout element="Thumbnail" widget="ImageGalleryWidget" configuration="{useformat:true}" />
				<layout element="Content" widget="HtmlWidget"
						configuration="height:400px,link,anchor,source,downloadgallery,formatselect"/>
			</layouts>
			<validationrules/>
			<relations/>
			<searchsettings containerPageOnly="false"/>
		</xsd:appinfo>
	</xsd:annotation>

</xsd:schema>

=== anhtuan161295/com.my.express.news/src/main/vfs/sites/default/express-news/.content/article/article-00019.xml
<?xml version="1.0" encoding="UTF-8"?>

<ExpressNewsArticles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="opencms://system/modules/com.my.express.news/schemas/article.xsd">
  <ExpressNewsArticle language="en">
    <Title><![CDATA[Add a new title here]]></Title>
    <ShortDescription/>
    <Thumbnail/>
    <VideoLink/>
    <Content/>
    <Date>0</Date>
    <Comment/>
    <View/>
    <Like/>
  </ExpressNewsArticle>
</ExpressNewsArticles>
